### ISSUE TITLE
Campurile de persoana juridica apar desii este selectata persoana fizica

### ISSUE THREAD

**Issue by atxpixel** [Robertutzu/grc-romanian-fields#1]
Cand trec din "shopping cart" in finalizarea comenzii, desii este selectat " Persoana fizica" apar campurile de persoana juridica.
Daca apas inca o data pe persoana fizica, dispar.
Video: 

Also: cum fac sa scot campurile: CONT SI BANCA ? si in locul lor cont sa pun "denumirea companiei" iar banca sa il scot de tot ? 

Video: https://youtu.be/fgCgiH-RZkY

**Comment by robertcezar** [comment]
vezi aici e pluginul mantained: https://wordpress.org/plugins/romanian-billing-fields/

**Comment by atxpixel** [comment]
Acesta este instalat
